'use client';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {Design,products} from '@/lib/presswerk/catalog';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';

export async function designCanvas(design:Design,max=1600){const p=products.find(p=>p.id===design.productId)!;const c=document.createElement('canvas');const scale=max/Math.max(p.width,p.height);c.width=Math.round(p.width*scale);c.height=Math.round(p.height*scale);const ctx=c.getContext('2d')!;ctx.fillStyle=design.background;ctx.fillRect(0,0,c.width,c.height);for(const l of design.layers){ctx.save();ctx.translate(l.x/100*c.width,l.y/100*c.height);ctx.rotate(l.rotation*Math.PI/180);ctx.globalAlpha=l.opacity;ctx.fillStyle=l.color;if(l.type==='text'){ctx.font=`${l.weight||700} ${l.size/100*c.width}px ${l.font||'Arial'}`;ctx.textBaseline='top';l.text.split('\n').forEach((line,i)=>ctx.fillText(line,0,i*l.size/100*c.width*1.1));}else if(l.type==='shape'){ctx.fillRect(0,0,(l.width||30)/100*c.width,(l.height||25)/100*c.height);}else if(l.src){const im=new Image();im.src=l.src;await im.decode();ctx.drawImage(im,0,0,(l.width||45)/100*c.width,(l.height||40)/100*c.height);}ctx.restore();}return c;}
export default function Mockup({design,spin=false}:{design:Design;spin?:boolean}){const host=useRef<HTMLDivElement>(null);const [failed,setFailed]=useState(false);useEffect(()=>{const el=host.current;if(!el)return;let disposed=false;let renderer:THREE.WebGLRenderer;let observer:ResizeObserver;let controls:OrbitControls;let raf=0;let scene:THREE.Scene;const boot=async()=>{try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor('#e9e9e7',1);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;el.appendChild(renderer.domElement);scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(34,1,.1,100);camera.position.set(0,1.1,7.7);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=3.5;controls.maxDistance=12;controls.autoRotate=spin;controls.autoRotateSpeed=1.2;controls.target.set(0,.1,0);scene.add(new THREE.HemisphereLight(0xffffff,0x686675,3));const light=new THREE.DirectionalLight(0xffffff,4);light.position.set(-3,6,5);light.castShadow=true;light.shadow.mapSize.set(1024,1024);scene.add(light);const fill=new THREE.DirectionalLight(0xc7d4ff,1.7);fill.position.set(5,1,-2);scene.add(fill);const canvas=await designCanvas(design);if(disposed)return;const map=new THREE.CanvasTexture(canvas);map.colorSpace=THREE.SRGBColorSpace;const printMat=new THREE.MeshStandardMaterial({map,roughness:design.finish==='Gloss laminate'?.2:.65,metalness:design.finish==='Foil accent'?.3:0});const white=new THREE.MeshStandardMaterial({color:0xfaf9f5,roughness:.45});const group=new THREE.Group();group.rotation.y=-.3;group.rotation.x=.05;const p=products.find(p=>p.id===design.productId)!;
 if(p.id==='mug'||p.id==='bottle'){const body=new THREE.Mesh(new THREE.CylinderGeometry(.85,.8,1.8,96,1,false),[printMat,white,white]);body.castShadow=true;group.add(body);const handle=new THREE.Mesh(new THREE.TorusGeometry(.48,.115,16,48,Math.PI*1.55),white);handle.position.set(1,0,0);handle.rotation.z=-Math.PI*.77;group.add(handle);const inner=new THREE.Mesh(new THREE.CylinderGeometry(.74,.74,.13,64),new THREE.MeshStandardMaterial({color:0xdad9d3}));inner.position.y=.906;group.add(inner);group.rotation.y=.7;
 }else if(p.category==='Apparel'){const s=new THREE.Shape();s.moveTo(-.55,1.3);s.lineTo(-1.35,.9);s.lineTo(-1.65,.2);s.lineTo(-1.08,-.05);s.lineTo(-.86,.3);s.lineTo(-.85,-1.4);s.lineTo(.85,-1.4);s.lineTo(.86,.3);s.lineTo(1.08,-.05);s.lineTo(1.65,.2);s.lineTo(1.35,.9);s.lineTo(.55,1.3);s.quadraticCurveTo(0,.85,-.55,1.3);const body=new THREE.Mesh(new THREE.ExtrudeGeometry(s,{depth:.12,bevelEnabled:true,bevelSegments:3,steps:1,bevelSize:.055,bevelThickness:.05}),new THREE.MeshStandardMaterial({color:0xf5f4ef,roughness:.96}));body.castShadow=true;group.add(body);const print=new THREE.Mesh(new THREE.PlaneGeometry(1.25,1.5),printMat);print.position.set(0,-.12,.19);group.add(print);
 }else{let w=3.3,h=w*p.height/p.width;if(h>3){h=3;w=h*p.width/p.height;}const depth=p.category==='Packaging'?.7:p.id==='canvas'?.13:.035;const mats=[white,white,white,white,printMat,white];const panel=new THREE.Mesh(new THREE.BoxGeometry(w,h,depth),mats);panel.castShadow=true;group.add(panel);if(p.id==='cards'){for(let i=1;i<7;i++){const card=new THREE.Mesh(new THREE.BoxGeometry(w,h,.023),white);card.position.set(i*.018,-i*.008,-i*.028);group.add(card);}}}
 scene.add(group);const ground=new THREE.Mesh(new THREE.PlaneGeometry(50,50),new THREE.ShadowMaterial({opacity:.12}));ground.rotation.x=-Math.PI/2;ground.position.y=-1.55;ground.receiveShadow=true;scene.add(ground);const resize=()=>{if(!el||disposed)return;const w=el.clientWidth,h=el.clientHeight;renderer.setSize(w,h);camera.aspect=w/Math.max(1,h);camera.updateProjectionMatrix();};observer=new ResizeObserver(resize);observer.observe(el);resize();const tick=()=>{if(disposed)return;controls.update();renderer.render(scene,camera);raf=requestAnimationFrame(tick);};tick();}catch{if(!disposed)setFailed(true);}};boot();return()=>{disposed=true;cancelAnimationFrame(raf);observer?.disconnect();controls?.dispose();scene?.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>{(m as THREE.MeshStandardMaterial).map?.dispose();m.dispose();});}});renderer?.dispose();renderer?.domElement.remove();};},[design,spin]);return <div className="mockup-webgl" ref={host}>{failed&&<div className="empty-state"><p>3D preview is unavailable in this browser. The artwork canvas and exports remain available.</p></div>}<span className="mockup-instruction">Drag to rotate · Scroll to zoom · Illustrative material appearance</span></div>;}
