import type { Metadata } from "next";
import { ArrowUpRight, Eye, Network, Scale, Waves } from "lucide-react";
import { SiteNav } from "@/components/site-nav";
import { SiteFooter } from "@/components/site-footer";
import { PageHero } from "@/components/page-hero";
import { AboutVisual } from "@/components/editorial-figures";
export const metadata: Metadata={title:"About",description:"The strategy, principles and Newfoundland-to-Canada ambition behind KINGXFORD Agency."};
export default function AboutPage(){return <main className="site-shell"><SiteNav/><PageHero index="08" eyebrow="NEWFOUNDLAND-BORN · CANADA-READY" title="Built at the edge." accent="Made to lead." description="KINGXFORD is being built for organizations that want the strategic depth of a serious agency, the craft of a production house and the operating clarity of a modern product company."/>
 <section className="about-belief content-section"><div className="section-kicker"><span>01</span> OUR BELIEF</div><div className="split-statement"><h2>Attention without action<br/><em>is noise.</em></h2><div><p className="large-copy">We connect what the market sees with what the business needs people to do next.</p><p>That means creative and performance are one job. Content carries a strategy. Technology removes friction. Data improves judgment. AI accelerates the workflow, while people remain responsible for the work.</p></div></div></section>
 <AboutVisual />
 <section className="principle-grid content-section dark-block"><article><Waves/><span>01</span><h3>Read the conditions.</h3><p>Newfoundland teaches attention to weather, distance and limited resources. We translate that instinct into sharper research and deliberate choices.</p></article><article><Eye/><span>02</span><h3>Send a clear signal.</h3><p>A market should understand why the brand matters before it is asked to care about a campaign.</p></article><article><Network/><span>03</span><h3>Connect the system.</h3><p>Strategy, creative, production, media, digital and sales work better when they share one commercial objective.</p></article><article><Scale/><span>04</span><h3>Prove before scaling.</h3><p>We prefer controlled tests, inspectable evidence and honest learning to theatre, vanity metrics and guaranteed claims.</p></article></section>
 <section className="ambition-section content-section coral-block"><div><div className="section-kicker"><span>→</span> THE AMBITION</div><h2>Canada&apos;s most useful independent agency—<em>city by city.</em></h2></div><div><p>We begin in St. John&apos;s with care, accessibility and accountability. Expansion follows real relationships, market knowledge and qualified local delivery—not a map full of imaginary offices.</p><p>The long-term model combines a senior core, specialist collaborators and transparent production partners. Every project should make it clear who is responsible and how the work is delivered.</p><a className="rule-link" href="/start">Build with us from the beginning <ArrowUpRight/></a></div></section>
 <section className="proof-standard content-section"><span>PROOF, NOT POSTURING.</span><h2>No borrowed logos.<br/>No mystery metrics.</h2><p>Until client work is publishable, demonstrations are labelled as concepts. Future case studies will show objective, baseline, scope, dates, source, measurement window and limitations—not just an attractive mockup and a heroic percentage.</p></section><SiteFooter/></main>}
