import type { Metadata } from "next";
import { ArrowUpRight, Eye, Network, Scale, Waves } from "lucide-react";
import { SiteNav } from "@/components/site-nav";
import { SiteFooter } from "@/components/site-footer";
import { PageHero } from "@/components/page-hero";
import { AboutVisual } from "@/components/editorial-figures";
export const metadata: Metadata={ alternates: { canonical: "/about" },title:"About",description:"The strategy, principles and Newfoundland-to-Canada ambition behind AVALON Creative Group."};
export default function AboutPage(){return <main className="site-shell"><SiteNav/><PageHero index="08" eyebrow="MEET AVALON CREATIVE GROUP" title="Independent minds." accent="Shared ambition." description="Avalon brings the perspective of a strategy partner, the craft of a creative studio and the discipline of a digital product team to one connected group."/>
 <section className="about-belief content-section"><div className="section-kicker"><span>01</span> OUR BELIEF</div><div className="split-statement"><h2>Attention without action<br/><em>is noise.</em></h2><div><p className="large-copy">We connect what the market sees with what the business needs people to do next.</p><p>That means creative and performance are one job. Content carries a strategy. Technology removes friction. Data improves judgment. AI accelerates the workflow, while people remain responsible for the work.</p></div></div></section>
 <AboutVisual />
 <section className="principle-grid content-section dark-block"><article><Waves/><span>01</span><h3>Read the conditions.</h3><p>Newfoundland teaches attention to weather, distance and limited resources. We translate that instinct into sharper research and deliberate choices.</p></article><article><Eye/><span>02</span><h3>Send a clear signal.</h3><p>A market should understand why the brand matters before it is asked to care about a campaign.</p></article><article><Network/><span>03</span><h3>Connect the system.</h3><p>Strategy, creative, production, media, digital and sales work better when they share one commercial objective.</p></article><article><Scale/><span>04</span><h3>Prove before scaling.</h3><p>Controlled tests, inspectable evidence and clear learning guide the next investment.</p></article></section>
 <section className="ambition-section content-section coral-block"><div><div className="section-kicker"><span>→</span> THE AMBITION</div><h2>A Canadian perspective.<br/><em>A wider ambition.</em></h2></div><div><p>We begin in St. John&apos;s with care, accessibility and accountability. Expansion follows real relationships, market knowledge and qualified local delivery.</p><p>The long-term model combines a senior core, specialist collaborators and transparent production partners. Every project should make it clear who is responsible and how the work is delivered.</p><a className="rule-link" href="/start">Build with us from the beginning <ArrowUpRight/></a></div></section>
 <section className="proof-standard content-section"><span>OUR STANDARD OF EVIDENCE</span><h2>Clear provenance.<br/>Meaningful evidence.</h2><p>Completed projects show real websites, their scope and original previews. Creative explorations are labelled as concepts. Performance case studies require a stated baseline, dates, data source, measurement window and relevant limitations.</p></section><SiteFooter/></main>}
