import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {PGlite} from '@electric-sql/pglite';
import {initialDesign,calculateQuote} from '../lib/presswerk/catalog.ts';
import {designFingerprint} from '../lib/presswerk/design-identity.ts';
const db=new PGlite();
await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
create schema auth; create schema storage;
create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth,storage to authenticated,service_role;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);
alter table storage.objects enable row level security; grant select,insert on storage.objects to authenticated;
create function storage.foldername(name text) returns text[] language sql immutable as $$select string_to_array(name,'/')$$;
alter default privileges in schema public grant all on tables to anon,authenticated;`);
await db.exec(await fs.readFile(new URL('../database/schema.sql',import.meta.url),'utf8'));
await db.exec(await fs.readFile(new URL('../database/platform.sql',import.meta.url),'utf8'));
const alice=randomUUID(),bob=randomUUID(),viewer=randomUUID(),wa=randomUUID(),wb=randomUUID(),project=randomUUID();
await db.query('insert into auth.users values($1,$2,now()),($3,$4,now()),($5,$6,now())',[alice,'alice@example.test',bob,'bob@example.test',viewer,'viewer@example.test']);
async function as(user,role='authenticated'){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false),set_config('request.jwt.claims',$2,false)",[user||'',JSON.stringify({sub:user||undefined,role})]);await db.exec('set role '+role);}
const q=async(sql,args=[])=>db.query(sql,args);
async function rejected(fn,pattern){await assert.rejects(fn,pattern);}
await as(alice);await q('insert into public.pw_workspaces(id,owner_id,name) values($1,$2,$3)',[wa,alice,'Alice Print']);
await as(bob);await q('insert into public.pw_workspaces(id,owner_id,name) values($1,$2,$3)',[wb,bob,'Bob Print']);
assert.equal((await q('select id from public.pw_workspaces')).rows.length,1);
await rejected(()=>q('insert into public.pw_workspaces(owner_id,name) values($1,$2)',[alice,'Impersonation']),/row-level|owner/);
await as(alice);
const d={...initialDesign(),id:project};
await q('insert into public.pw_projects(id,workspace_id,design) values($1,$2,$3)',[project,wa,JSON.stringify(d)]);
const roundtrip=(await q('select design from public.pw_projects where id=$1',[project])).rows[0].design;
assert.equal(designFingerprint(d),designFingerprint(roundtrip));
await rejected(()=>q('update public.pw_projects set design=$1 where id=$2',[JSON.stringify({...d,quantity:-1}),project]),/Invalid design/);
await rejected(()=>q('update public.pw_projects set design=$1 where id=$2',[JSON.stringify({...d,layers:[{...d.layers[0],x:null}]}),project]),/Invalid design/);
await q('update public.pw_projects set design=$1 where id=$2 and version=1',[JSON.stringify({...d,name:'Second version'}),project]);
assert.equal((await q('select version from public.pw_projects where id=$1',[project])).rows[0].version,2);
assert.equal((await q('select * from public.pw_revisions where project_id=$1',[project])).rows.length,2);
assert.equal((await q('update public.pw_projects set design=$1 where id=$2 and version=1 returning id',[JSON.stringify(d),project])).rows.length,0);
await rejected(()=>q('update public.pw_projects set workspace_id=$1 where id=$2',[wb,project]),/permission denied/);
await rejected(()=>q('update public.pw_projects set design=$1 where id=$2',['{}',project]),/Invalid design/);
await rejected(()=>q('update public.pw_workspaces set brand=$1 where id=$2',['{}',wa]),/check constraint/);
await rejected(()=>q('update public.pw_projects set design=$1 where id=$2',[JSON.stringify({...d,layers:[{...d.layers[0],type:'image',assetPath:wb+'/foreign.png'}]}),project]),/another workspace/);
await rejected(()=>q('insert into public.pw_proofs(workspace_id,project_id,version,approved_at) values($1,$2,2,now())',[wa,project]),/permission denied/);
await rejected(()=>q('insert into public.pw_orders(workspace_id,project_id,version,idempotency_key,estimate) values($1,$2,2,$3,$4)',[wa,project,randomUUID(),JSON.stringify({total:.01})]),/permission denied/);
await q('insert into storage.objects(bucket_id,name) values($1,$2)',['presswerk-artwork',wa+'/artwork.png']);
await as(bob);
assert.equal((await q('select * from public.pw_projects')).rows.length,0);
assert.equal((await q('select * from public.pw_revisions')).rows.length,0);
assert.equal((await q('select * from storage.objects')).rows.length,0);
await rejected(()=>q('insert into storage.objects(bucket_id,name) values($1,$2)',['presswerk-artwork',wa+'/bad.png']),/row-level/);
await rejected(()=>q('insert into public.pw_proofs(workspace_id,project_id,version) values($1,$2,2)',[wb,project]),/row-level/);
await as(alice);
const invited=(await q("select public.pw_team($1,'invite',$2,'viewer') as result",[wa,'viewer@example.test'])).rows[0].result;
await as(bob);await rejected(()=>q("select public.pw_team($1,'accept','','viewer',$2)",[wa,invited.token]),/another account/);
await as(viewer);await q("select public.pw_team($1,'accept','','viewer',$2)",[wa,invited.token]);
assert.equal((await q('select * from public.pw_projects')).rows.length,1);
assert.equal((await q('update public.pw_projects set design=$1 where id=$2 returning id',[JSON.stringify(d),project])).rows.length,0);
await rejected(()=>q("select public.pw_keys($1,'create','Bad key')",[wa]),/administrator/);
await rejected(()=>q("select public.pw_team($1,'accept','','viewer',$2)",[wa,invited.token]),/invalid/);
await as(null,'service_role');
const order=randomUUID(),estimate={...calculateQuote({...d,shipping:0}),quantity:d.quantity,city:d.city,projectName:d.name};
await q('insert into public.pw_orders(id,workspace_id,project_id,version,idempotency_key,estimate,created_by) values($1,$2,$3,2,$4,$5,$6)',[order,wa,project,randomUUID(),JSON.stringify(estimate),alice]);
await rejected(()=>q('insert into public.pw_orders(workspace_id,project_id,version,idempotency_key,estimate,created_by) values($1,$2,2,$3,$4,$5)',[wa,project,randomUUID(),JSON.stringify(estimate),bob]),/Workspace access/);
await as(alice);
await rejected(()=>q("update public.pw_orders set status='Printing' where id=$1",[order]),/next production stage/);
await rejected(()=>q("update public.pw_orders set status='Ready to produce' where id=$1",[order]),/proof approval/);
await q('insert into public.pw_proofs(workspace_id,project_id,version) values($1,$2,2)',[wa,project]);
await q("update public.pw_orders set status='Ready to produce' where id=$1",[order]);
await q("update public.pw_orders set status='Printing' where id=$1",[order]);
assert.equal((await q('select * from public.pw_order_events where order_id=$1',[order])).rows.length,3);
await rejected(()=>q('update public.pw_orders set estimate=$1 where id=$2',['{"total":0}',order]),/permission denied/);
for(let i=0;i<30;i++)await q('select public.pw_consume_ai($1)',[wa]);
await rejected(()=>q('select public.pw_consume_ai($1)',[wa]),/allowance/);
const key=(await q("select public.pw_keys($1,'create','Storefront') as result",[wa])).rows[0].result.key;
const list=(await q("select public.pw_keys($1,'list') as result",[wa])).rows[0].result;
assert.equal(key.length,72);assert.equal(JSON.stringify(list).includes(key),false);
await as(null,'anon');
await rejected(()=>q('select * from public.pw_projects'),/permission denied/);
const response=(await q("select public.pw_platform_request($1,'orders') as result",[key])).rows[0].result;
assert.equal(response.orders.length,1);assert.equal(response.orders[0].id,order);
await rejected(()=>q("select public.pw_platform_request($1,'orders')",['pw_live_'+'f'.repeat(64)]),/invalid/);
await as(alice);await q("select public.pw_keys($1,'revoke','',$2)",[wa,list[0].id]);
await as(null,'anon');await rejected(()=>q("select public.pw_platform_request($1,'orders')",[key]),/invalid or revoked/);
await db.close();
console.log('PASS: isolated tenants, roles, private storage, immutable revisions, conflicts, proof integrity, trusted order creation, audited transitions, AI quotas, invitations and API key revocation.');
