"use client";

import { useId, useState } from "react";
import { CalendarDays, ChevronLeft, ChevronRight, Download, Plus, Upload } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { CHANNELS, csv, uid, validDate, type Campaign } from "@/lib/campaign";
import { EDITORIAL_HEADERS, editorialIcs, editorialTemplate, mergeEditorial, parseEditorialCsv, shiftEditorial, type EditorialItem } from "@/lib/editorial";
import styles from "./editorial-workbench.module.css";

export type WorkbenchProps = { c: Campaign; update: (patch: Partial<Campaign>, action: string, brief?: boolean) => void; notify: (message: string) => void };
function download(name: string, content: string, type: string) { const url = URL.createObjectURL(new Blob([content], { type })); const a = document.createElement("a"); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }

export function ContentWorkbench({ c, update, notify }: WorkbenchProps) {
  const [month, setMonth] = useState(() => (c.brief.launchDate || new Date().toISOString()).slice(0, 7));
  const [channel, setChannel] = useState("All"), [selected, setSelected] = useState<string[]>([]), [shift, setShift] = useState("7");
  const [compose, setCompose] = useState(false), [draftTitle, setDraftTitle] = useState(""), [draftCopy, setDraftCopy] = useState(""), [draftDate, setDraftDate] = useState(""), [draftChannel, setDraftChannel] = useState<typeof CHANNELS[number]>("Organic");
  const [csvSource, setCsvSource] = useState(""), [preview, setPreview] = useState<EditorialItem[] | null>(null), [error, setError] = useState("");
  const fileId = useId();
  const filtered = c.content.filter((x) => channel === "All" || x.channel === channel);
  const activeIds = selected.filter((id) => c.content.some((x) => x.id === id));
  const scheduled = filtered.filter((x) => x.date.startsWith(month));
  const start = new Date(`${month}-01T12:00:00Z`), dayCount = new Date(Date.UTC(start.getUTCFullYear(), start.getUTCMonth() + 1, 0)).getUTCDate();
  const offset = (start.getUTCDay() + 6) % 7;
  function moveMonth(delta: number) { const d = new Date(start); d.setUTCMonth(d.getUTCMonth() + delta); const next = d.toISOString().slice(0,7); if (next >= "2000-01" && next <= "2099-12") setMonth(next); }
  function safe(action: () => void) { try { action(); setError(""); } catch (e) { setError(e instanceof Error ? e.message : "Check the supplied calendar."); } }
  function createDraft() {
    if (!draftTitle.trim() || !draftCopy.trim()) { setError("Give the draft a title and copy before adding it."); return; }
    if (draftDate && (!validDate(draftDate) || draftDate < "2000-01-01" || draftDate > "2099-12-31")) { setError("Choose a valid planning date from 2000–2099."); return; }
    if (c.content.length >= 200) { setError("The calendar holds 200 items. Export old work before making room."); return; }
    update({ content: [...c.content, { id: uid(), title: draftTitle.trim(), copy: draftCopy.trim(), date: draftDate, channel: draftChannel, status: "Draft", revision: c.revision }] }, "Added original editorial draft");
    if (draftDate) setMonth(draftDate.slice(0,7)); setCompose(false); setDraftTitle(""); setDraftCopy(""); setError(""); notify("Draft added to this campaign. Review it in the content library below.");
  }
  return <section className={styles.workbench} aria-labelledby="editorial-workbench-title">
    <header className={styles.header}><div><span className={styles.eyebrow}>THE EDITORIAL DESK</span><h2 id="editorial-workbench-title">See the story taking shape.</h2><p>A shared calendar, original drafts and a clean handoff to your publishing team.</p></div><Button onClick={() => setCompose(!compose)} aria-expanded={compose}><Plus size={18} /> Write a draft</Button></header>
    <div className={styles.metrics}><div><strong>{c.content.length}</strong><span>editorial items</span></div><div><strong>{c.content.filter((x) => x.status === "In review").length}</strong><span>awaiting review</span></div><div><strong>{c.content.filter((x) => x.status === "Approved" && x.revision === c.revision).length}</strong><span>current approvals</span></div><div><strong>{c.content.filter((x) => !x.date).length}</strong><span>need a date</span></div></div>
    {compose && <div className={styles.composer}><h3>Write an original draft</h3><label>Editorial title<Input maxLength={180} value={draftTitle} onChange={(e) => setDraftTitle(e.target.value)} /></label><div className={styles.two}><label>Draft channel<select value={draftChannel} onChange={(e) => setDraftChannel(e.target.value as typeof draftChannel)}>{CHANNELS.map((x) => <option key={x}>{x}</option>)}</select></label><label>Draft planning date<Input type="date" min="2000-01-01" max="2099-12-31" value={draftDate} onChange={(e) => setDraftDate(e.target.value)} /></label></div><label>Original copy<Textarea rows={5} maxLength={5000} value={draftCopy} onChange={(e) => setDraftCopy(e.target.value)} /></label><div className={styles.actions}><Button onClick={createDraft}>Add to campaign</Button><Button variant="outline" onClick={() => setCompose(false)}>Close composer</Button></div></div>}
    <div className={styles.toolbar}><div className={styles.actions}><Button variant="outline" aria-label="Previous calendar month" onClick={() => moveMonth(-1)}><ChevronLeft /></Button><strong>{start.toLocaleDateString("en-CA", { month: "long", year: "numeric", timeZone: "UTC" })}</strong><Button variant="outline" aria-label="Next calendar month" onClick={() => moveMonth(1)}><ChevronRight /></Button></div><label>Calendar channel<select value={channel} onChange={(e) => setChannel(e.target.value)}>{["All", ...CHANNELS].map((x) => <option key={x}>{x}</option>)}</select></label></div>
    <div className={styles.calendarWrap}><div className={styles.calendar} aria-label="Editorial month calendar">{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((d) => <div className={styles.weekday} key={d}>{d}</div>)}{Array.from({length: offset}, (_, i) => <div className={styles.blankDay} key={`blank-${i}`} />)}{Array.from({ length: dayCount }, (_, i) => { const date = `${month}-${String(i + 1).padStart(2,"0")}`, items = scheduled.filter((x) => x.date === date); return <div className={styles.day} key={date}><span>{i + 1}</span>{items.map((item) => <button type="button" key={item.id} aria-pressed={activeIds.includes(item.id)} onClick={() => setSelected(activeIds.includes(item.id) ? activeIds.filter((id) => id !== item.id) : [...activeIds, item.id])}><small>{item.channel} · {item.revision !== c.revision ? "Needs refresh" : item.status}</small>{item.title}</button>)}</div>; })}</div></div>
    <p className={styles.note}>{scheduled.length} items this month. Select cards to reschedule or request review. Dates are planning dates; the calendar does not publish content.</p>
    <details className={styles.detail}><summary>Unscheduled work · {filtered.filter((x) => !x.date).length}</summary><div className={styles.unscheduled}>{filtered.filter((x) => !x.date).map((item) => <label key={item.id}><input type="checkbox" checked={activeIds.includes(item.id)} onChange={(e) => setSelected(e.target.checked ? [...activeIds,item.id] : activeIds.filter((id) => id !== item.id))} />{item.channel} · {item.title}</label>)}{!filtered.some((x) => !x.date) && <p>Every item in this channel has a planning date.</p>}</div></details>
    <div className={styles.bulk}><strong>{activeIds.length} selected</strong><label>Shift scheduled items by days<Input type="number" min={-365} max={365} step={1} value={shift} onChange={(e) => setShift(e.target.value)} /></label><Button variant="outline" disabled={!activeIds.length || !shift.trim()} onClick={() => safe(() => { const items = shiftEditorial(c.content, activeIds, Number(shift)); if (!c.content.some((x) => activeIds.includes(x.id) && x.date)) throw new Error("Select at least one scheduled item to shift."); update({content: items}, `Shifted selected calendar items by ${shift} days; approvals reset`); notify("Scheduled items moved and returned to Draft for review."); })}>Shift dates</Button><Button variant="outline" disabled={!activeIds.length} onClick={() => { update({content:c.content.map((x) => activeIds.includes(x.id) ? {...x,status:"In review"} : x)}, "Requested editorial review for selected items"); setSelected([]); notify("Selected items moved to In review. Older brief versions still need refresh before approval."); }}>Request review</Button><Button variant="ghost" disabled={!activeIds.length} onClick={() => setSelected([])}>Clear selection</Button></div>
    <details className={styles.detail}><summary><Upload size={18} /> Import an editorial calendar</summary><div className={styles.importer}><p>CSV columns: date, channel, title, copy. Every imported item starts as a draft against this brief. Exact duplicates are skipped.</p><label htmlFor={fileId}>Choose calendar CSV</label><input id={fileId} type="file" accept=".csv,text/csv" onChange={async (e) => { const file = e.target.files?.[0]; if (!file) return; if (file.size > 1_000_000) { setError("Keep the calendar below 1 MB."); return; } try { setCsvSource(await file.text()); setPreview(null); setError(""); } catch { setError("The file could not be read."); } e.target.value=""; }} /><label>Or paste calendar CSV<Textarea rows={5} value={csvSource} maxLength={1_000_000} onChange={(e) => { setCsvSource(e.target.value); setPreview(null); }} /></label><div className={styles.actions}><Button variant="outline" onClick={() => download("avalon-calendar-template.csv", editorialTemplate(), "text/csv;charset=utf-8")}>Download template</Button><Button disabled={!csvSource.trim()} onClick={() => safe(() => setPreview(parseEditorialCsv(csvSource,c.revision)))}>Preview import</Button></div>{preview && <div className={styles.preview}><h3>{preview.length} drafts ready for review</h3><ul>{preview.slice(0,5).map((x) => <li key={x.id}>{x.date || "Unscheduled"} · {x.channel} · {x.title}</li>)}</ul>{preview.length > 5 && <p>And {preview.length - 5} more items.</p>}<Button onClick={() => safe(() => { const result = mergeEditorial(c.content,preview.map((x) => ({...x,revision:c.revision}))); if (result.added) update({content:result.items}, `Imported ${result.added} editorial drafts`); setPreview(null); setCsvSource(""); notify(`${result.added} drafts added; ${result.skipped} exact duplicates skipped.`); })}>Add drafts to campaign</Button></div>}</div></details>
    {error && <p role="alert" className={styles.error}>{error}</p>}
    <div className={styles.actions}><Button variant="outline" disabled={!c.content.some((x) => validDate(x.date))} onClick={() => download("avalon-editorial-plan.ics",editorialIcs(c),"text/calendar;charset=utf-8")}><CalendarDays size={18} /> Export to calendar</Button><Button variant="outline" disabled={!c.content.length} onClick={() => download("avalon-editorial-handoff.csv",csv([[...EDITORIAL_HEADERS,"status","brief revision"],...c.content.map((x) => [x.date,x.channel,x.title,x.copy,x.status,x.revision])]),"text/csv;charset=utf-8")}><Download size={18} /> Export editorial handoff</Button></div>
  </section>;
}
