"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, Check, FileText, Layers3, Network } from "lucide-react";
import styles from "./journey-explorer.module.css";

const routes = [
  {name:"Launch a campaign",title:"From a clear brief to work ready for the world.",description:"Connect strategy, creative direction, production and release. Every deliverable keeps the decisions that shaped it.",accent:"coral",result:"A reviewed launch package",items:["Shared brief and specialist plans","Assets with versions and review decisions","Owners, delivery dates and release checks"],steps:[{title:"Set the direction",detail:"Audience · offer · evidence",view:"brief"},{title:"Build your specialist team",detail:"Connected plans · source context",view:"workflows"},{title:"Make and review the work",detail:"Original files · versions · decisions",view:"delivery"},{title:"Prepare the release",detail:"Evidence · approvals · handoff",view:"proof"}]},
  {name:"Build a content system",title:"One point of view. A calendar full of possibilities.",description:"Carry a campaign idea into original drafts, channel adaptations and a practical editorial calendar. Bring your own work or start with a structured plan.",accent:"lilac",result:"An editorial system you can run",items:["A shared voice and editorial direction","Original drafts, imports and a visual calendar","Review status and publishing-team exports"],steps:[{title:"Define your point of view",detail:"Brand · audience · voice",view:"brief"},{title:"Plan the editorial direction",detail:"Creative and editorial specialists",view:"agents"},{title:"Write and schedule",detail:"Drafts · calendar · batch planning",view:"content"},{title:"Deliver the approved work",detail:"Asset register · handoff package",view:"delivery"}]},
  {name:"Improve performance",title:"Turn campaign evidence into a better next decision.",description:"Bring in real results, find the gaps and compare like-for-like periods. Model the economics, then set up a specific test with an accountable owner.",accent:"lime",result:"A decision backed by your evidence",items:["Sourced results with channel coverage checks","Commercial scenarios and break-even planning","Experiment plans and follow-up tasks"],steps:[{title:"Import what happened",detail:"Actual results · dates · sources",view:"performance"},{title:"Understand the economics",detail:"Channel efficiency · contribution",view:"media"},{title:"Design the next test",detail:"Hypothesis · sample · decision rule",view:"experiments"},{title:"Give the decision an owner",detail:"Actions · dates · evidence",view:"production"}]},
] as const;
export function JourneyExplorer(){
  const [active,setActive]=useState(0),route=routes[active];
  return <div data-journey="explorer" className={`${styles.explorer} ${styles[route.accent] ?? ""}`}>
    <div data-journey="tabs" className={styles.routeTabs} role="group" aria-label="Choose your working route">{routes.map((r,i)=><button key={r.name} aria-pressed={active===i} onClick={()=>setActive(i)}><span>0{i+1}</span>{r.name}<ArrowUpRight size={18}/></button>)}</div>
    <div data-journey="canvas" className={styles.canvas}><div className={styles.intro}><span className={styles.label}>YOUR AMBITION, CONNECTED</span><h3>{route.title}</h3><p>{route.description}</p><Link href={`/platform?view=${route.steps[0].view}`}>Start here <ArrowRight size={20}/></Link></div><div className={styles.route}><div className={styles.routeHeader}><Network size={19}/><span>One campaign. Shared context.</span></div><ol>{route.steps.map((step,i)=><li key={step.view}><Link href={`/platform?view=${step.view}`}><span className={styles.stepNumber}>0{i+1}</span><div><b>{step.title}</b><small>{step.detail}</small></div><ArrowUpRight size={18}/></Link></li>)}</ol><div className={styles.output}><Layers3 size={23}/><div><span>WHAT YOU BUILD</span><h4>{route.result}</h4></div></div></div></div>
    <div className={styles.bottom}><div>{route.items.map(x=><span key={x}><Check size={15}/>{x}</span>)}</div><Link href="/platform"><FileText size={18}/>Enter the workspace<ArrowUpRight size={18}/></Link></div>
  </div>;
}
