"use client";
import { useState } from "react";
import { Code2, Copy, Download, Eye, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { safeUrl, type Campaign } from "@/lib/campaign";
import { pageHandoff, webInsight } from "@/lib/editorial";
import type { WorkbenchProps } from "./editorial-workbench";
import styles from "./editorial-workbench.module.css";

export function WebWorkbench({c,notify}: WorkbenchProps) {
  const [keyword,setKeyword] = useState("");
  const [surface,setSurface] = useState<"search"|"page">("search");
  const insights=webInsight(c.web,keyword), url=safeUrl(c.brief.website);
  const schema = {"@context":"https://schema.org","@type":"WebPage",...(url?{url}:{}),name:c.web.title,description:c.web.description,inLanguage:"en-CA"};
  const schemaText=JSON.stringify(schema,null,2).replace(/</g,"\\u003c");
  function download(name:string,body:string,type:string) {const blob=URL.createObjectURL(new Blob([body],{type})); const a=document.createElement("a"); a.href=blob;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(blob),1000);}
  async function copy(text:string) {try {await navigator.clipboard.writeText(text);notify("Web handoff copied.");}catch {notify("Clipboard is unavailable. Download the handoff instead.");}}
  const hasCopy=!!(c.web.title.trim()||c.web.heading.trim()||c.web.body.trim());
  return <section className={styles.workbench} aria-labelledby="web-workbench-title">
    <header className={styles.header}><div><span className={styles.eyebrow}>THE WEB DESK</span><h2 id="web-workbench-title">Turn page copy into an experience.</h2><p>Preview your message, inspect its structure and prepare a developer handoff.</p></div><Eye size={28} /></header>
    <div className={styles.two}><div><div className={styles.actions} role="group" aria-label="Preview surface"><Button variant={surface==="search"?"default":"outline"} onClick={()=>setSurface("search")} aria-pressed={surface==="search"}><Search size={16} />Search preview</Button><Button variant={surface==="page"?"default":"outline"} onClick={()=>setSurface("page")} aria-pressed={surface==="page"}><Eye size={16} />Page preview</Button></div>
    {surface==="search"?<div className={styles.searchPreview}><span>{c.brief.brand||"Your brand"}</span><small>{url?new URL(url).hostname:"Add the website in Shared brief"}</small><h3>{c.web.title||"Your page title will appear here"}</h3><p>{c.web.description||"Write a useful search description in the page copy workbench below."}</p></div>:<div className={styles.pagePreview}><span>{c.brief.brand||"Your brand"}</span><h3>{c.web.heading||"A clear promise starts here."}</h3><p>{c.web.body||"Your supplied page copy appears here as you edit the workbench below."}</p><strong>{c.web.cta||"Your primary action"}</strong></div>}
    <p className={styles.note}>An editorial preview of supplied copy. Search engines may display a different title or snippet; this does not measure rankings or crawl the live site.</p></div>
    <div><div className={styles.metrics}><div><strong>{insights.words}</strong><span>words</span></div><div><strong>{insights.words?insights.readingMinutes:0}m</strong><span>estimated reading</span></div><div><strong>{insights.averageSentence}</strong><span>words per sentence</span></div></div><label>Focus phrase<Input maxLength={120} placeholder="e.g. wedding photography" value={keyword} onChange={(e)=>setKeyword(e.target.value)} /></label><p className={styles.note}>Check where your intended topic appears. This is literal phrase matching, not a ranking score.</p><ul className={styles.checklist}>{insights.placements.map((x)=><li key={x.field}><span>{x.field}</span><strong>{!keyword.trim()?"Add a phrase":x.present?"Present":"Not present"}</strong></li>)}</ul>{insights.averageSentence>25&&<p className={styles.error}>Long sentences may make this copy harder to scan. Review the audience and split complicated ideas.</p>}<p className={styles.note}>{insights.paragraphs} paragraphs. Reading time assumes about 200 words per minute; clarity needs editorial judgment.</p></div></div>
    <details className={styles.detail}><summary><Code2 size={18} />Structured data & developer handoff</summary><div className={styles.importer}><p>A minimal WebPage description built from your supplied fields. Review it before integrating into the website; it does not imply eligibility for rich results.</p><pre className={styles.code}>{schemaText}</pre><div className={styles.actions}><Button variant="outline" disabled={!hasCopy} onClick={()=>void copy(schemaText)}><Copy size={16}/>Copy JSON-LD</Button><Button variant="outline" disabled={!hasCopy} onClick={()=>download("avalon-webpage.json",schemaText,"application/ld+json")}><Download size={16}/>Download JSON-LD</Button><Button disabled={!hasCopy} onClick={()=>download("avalon-page-handoff.html",pageHandoff(c),"text/html;charset=utf-8")}>Export page prototype</Button></div></div></details>
    <div className={styles.actions}><Button variant="outline" disabled={!hasCopy} onClick={()=>download("avalon-web-review.md",webReport(c,keyword),"text/markdown;charset=utf-8")}><Download size={16}/>Download web review</Button></div>
  </section>;
}
function webReport(c:Campaign,keyword:string) {const i=webInsight(c.web,keyword);return `# ${c.brief.brand||c.name} · web review\n\nBrief revision: ${c.revision}\nDestination: ${safeUrl(c.brief.website)||"Not supplied"}\n\n## Supplied metadata\nTitle: ${c.web.title}\nDescription: ${c.web.description}\n\n## Page copy\n${c.web.heading}\n\n${c.web.body}\n\nAction: ${c.web.cta}\nImage alt: ${c.web.alt}\n\n## Editorial structure\n${i.words} words; ${i.paragraphs} paragraphs; approximately ${i.readingMinutes} minutes at 200 words/minute.\nFocus phrase: ${keyword||"Not specified"}\n${i.placements.map((x)=>`- ${x.field}: ${keyword?(x.present?"present":"not present"):"not evaluated"}`).join("\n")}\n\n## Manual verification\n- Check heading hierarchy, keyboard navigation and focus.\n- Test forms, success/error feedback and consent in the deployed site.\n- Verify that each material claim has evidence and every image has appropriate rights.\n- Check phone layout, loading behavior and links.\n\nGenerated from supplied copy. No live site crawl, legal review, ranking data or accessibility certification is included.\n`;}
